const state={user:null,documents:[],drafts:[],medications:[],metrics:[],metricEntries:[],overview:null,costSummary:null,testSessions:[],currentDraft:null,currentMedication:null,currentDocument:null,currentView:"overview",detailReturnView:"archive",detailTriggerId:null,viewScroll:{overview:0,home:0,metrics:0,ogtt:0,costs:0,archive:0},archiveTrashMode:false,labFilter:"all",previewIndex:0,authMode:"login",uploadItems:[],uploadRunning:false,uploadSummary:""};
const $=id=>document.getElementById(id);
const escapeHtml=value=>String(value??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const pulmonaryHospitalAliases=new Set(['上海市肺科医院','上海市职业病防治医院','上海市职业病防治院']);
function hospitalKey(value){
  const normalized=(value||'').normalize('NFKC').replace(/\s+/g,'');
  const parts=normalized.split(/[、,，;；\/／()（）]+/).filter(Boolean);
  return parts.length&&parts.every(part=>pulmonaryHospitalAliases.has(part))?'上海市肺科医院':normalized;
}
function toast(message){const el=$("toast");el.textContent=message;el.classList.add("show");clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove("show"),2600)}
function errorText(error){if(error?.status===401)return"登录已失效，请重新登录";return error?.message||"操作失败，请稍后重试"}
function today(){return new Date().toISOString().slice(0,10)}

const viewCopy={overview:["个人健康档案","数据概览","按当前档案成员完整数据汇总"],home:["健康档案","健康时间线","按主要日期整理已经确认的医疗资料"],metrics:["健康数据","健康指标","关注指标、日常记录与报告来源"],ogtt:["专项试验","OGTT","按明确试验分组查看各时点结果"],costs:["费用档案","医疗费用","按币种、年份与票据来源核对"],upload:["资料入口","上传资料","原件私密保存，模型结果需要人工确认"],pending:["人工核对","待确认资料","对照原件修正识别内容，再进入正式档案"],archive:["完整记录","原始资料档案","集中查看原件、结构化信息和检验结果"],drugs:["药品资料","药品管理","个人药箱、实际用药计划与状态历史"],detail:["原始资料","文档详情","原件与结构化信息对照查看"],admin:["系统管理","用户管理","创建一次性邀请并管理账号入口"]};
function showView(name,options={}){const previous=state.currentView||document.querySelector(".view.active")?.id.replace("view-","")||"overview";if(previous!==name&&previous!=="detail")state.viewScroll[previous]=window.scrollY;document.querySelectorAll(".view").forEach(el=>el.classList.toggle("active",el.id===`view-${name}`));document.querySelectorAll("[data-view]").forEach(el=>el.classList.toggle("active",el.dataset.view===name||(name==="detail"&&el.dataset.view===state.detailReturnView)));state.currentView=name;const copy=viewCopy[name]||viewCopy.overview;$("pageEyebrow").textContent=copy[0];$("pageTitle").textContent=copy[1];$("pageSubtitle").textContent=copy[2];if(options.refresh!==false){if(name==="overview")loadOverview();if(name==="metrics")loadMetrics();if(name==="ogtt")loadOgtt();if(name==="costs")loadCosts();if(name==="pending")loadDrafts();if(name==="archive")loadDocuments();if(name==="drugs")loadMedications();if(name==="admin")loadUsers()}if(options.restoreScroll)requestAnimationFrame(()=>window.scrollTo({top:state.viewScroll[name]||0,behavior:"auto"}));else if(previous!==name&&options.scrollToTop!==false)window.scrollTo({top:0,behavior:"auto"})}

function configureAuth(mode){state.authMode=mode;const titles={setup:["首次初始化","创建管理员账号","创建管理员"],login:["安全入口","登录健康档案","登录"],invite:["受邀注册","创建你的独立账号","接受邀请"]};const copy=titles[mode];$("authStep").textContent=copy[0];$("authTitle").textContent=copy[1];$("authSubmit").textContent=copy[2];$("authEmail").closest("label").classList.toggle("hidden",mode==="invite");$("authEmail").required=mode!=="invite";$("authPassword").autocomplete=mode==="login"?"current-password":"new-password";$("authConfirmLabel").classList.toggle("hidden",mode==="login");$("authConfirmPassword").required=mode!=="login";$("authConfirmPassword").value="";setAuthPasswordVisibility(false);$("authError").textContent="";}
function setAuthPasswordVisibility(visible){$("authPassword").type=visible?"text":"password";$("authConfirmPassword").type=visible?"text":"password";$("authPasswordVisibility").textContent=visible?"隐藏密码":"显示密码";$("authPasswordVisibility").setAttribute("aria-pressed",String(visible))}
async function bootstrap(){try{const system=await api.get("/api/system/status");$("modelStatus").textContent=system.model.configured?(system.model.fallback2_configured?(system.model.fallback_configured?"视觉解析服务已配置 · 2 个备用已配置":"视觉解析服务已配置 · 第二备用已配置"):system.model.fallback_configured?"视觉解析服务已配置 · 备用已配置":"视觉解析服务已配置"):"解析服务未配置";const token=new URLSearchParams(location.search).get("invite");if(token){configureAuth("invite");return}try{state.user=await api.get("/api/auth/me");await enterApp()}catch{const setup=await api.get("/api/setup/status");configureAuth(setup.required?"setup":"login")}}catch(error){configureAuth("login");$("authError").textContent="无法连接本地服务，请检查 Docker 服务状态"}}
async function handleAuth(event){event.preventDefault();const password=$("authPassword").value;$("authError").textContent="";if(state.authMode!=="login"&&password!==$("authConfirmPassword").value){$("authError").textContent="两次输入的密码不一致，请重新核对";$("authConfirmPassword").focus();return}try{if(state.authMode==="setup")state.user=await api.post("/api/setup/admin",{email:$("authEmail").value,password});else if(state.authMode==="invite")state.user=await api.post("/api/auth/register/invitation",{token:new URLSearchParams(location.search).get("invite"),password});else state.user=await api.post("/api/auth/login",{email:$("authEmail").value,password});history.replaceState({},"",location.pathname);await enterApp()}catch(error){$("authError").textContent=errorText(error)}}
async function enterApp(){$("view-auth").classList.add("hidden");$("appShell").classList.remove("hidden");$("userEmail").textContent=state.user.email;$("userInitial").textContent=state.user.email.slice(0,1).toUpperCase();$("userRole").textContent=state.user.role==="admin"?"管理员 · 资料仍保持私密":"普通用户";document.querySelectorAll(".admin-only").forEach(el=>el.classList.toggle("hidden",state.user.role!=="admin"));await window.loadProfiles?.();showView("overview",{refresh:false});await Promise.all([loadDocuments(),loadDrafts(),loadMedications(),loadOverview(),loadMetrics()])}

async function loadDocuments(){try{const result=await api.get(`/api/documents?limit=100&search=${encodeURIComponent($("archiveSearch")?.value||"")}`);state.documents=result.items;renderHome();if(state.archiveTrashMode&&window.loadTrashDocuments)await window.loadTrashDocuments();else renderArchive()}catch(error){if(error.status===401)return resetAuth();toast(errorText(error))}}
function renderHome(){
  const hospitalSelect=$("hospitalFilter");
  const currentHospital=hospitalSelect.value;
  const hospitals=[...new Set(state.documents.map(item=>hospitalKey(item.hospital)).filter(Boolean))]
    .sort((a,b)=>a.localeCompare(b,"zh-CN"));
  hospitalSelect.innerHTML='<option value="">全部医院</option>'+hospitals.map(name=>
    `<option value="${escapeHtml(name)}">${escapeHtml(name)}</option>`).join("");
  hospitalSelect.value=hospitals.includes(currentHospital)?currentHospital:"";
  const query=$("searchInput").value.trim().toLowerCase();
  const type=$("typeFilter").value;
  const hospital=hospitalSelect.value;
  const docs=state.documents.filter(doc=>{
    const hay=[doc.title,doc.hospital,hospitalKey(doc.hospital),doc.department,doc.document_type,
      doc.parsed_content,...(doc.key_information||[])].filter(Boolean).join(" ").toLowerCase();
    return (!query||hay.includes(query))&&(!type||doc.document_type===type)&&
      (!hospital||hospitalKey(doc.hospital)===hospital);
  });
  $("metricDocuments").textContent=docs.length;
  $("metricHospitals").textContent=new Set(docs.map(doc=>hospitalKey(doc.hospital)).filter(Boolean)).size;
  $("metricLatest").textContent=docs.map(doc=>doc.primary_date).filter(Boolean).sort().reverse()[0]||"—";
  const grouped={};
  docs.filter(doc=>doc.primary_date).forEach(doc=>(grouped[doc.primary_date]??=[]).push(doc));
  const dates=Object.keys(grouped).sort().reverse();
  $("timeline").innerHTML=dates.length?dates.map(date=>{
    const parts=date.split("-");
    const heading=parts.length===3?`${parts[0]}年${Number(parts[1])}月${Number(parts[2])}日`:date;
    return `<div class="timeline-group"><div class="timeline-date"><strong>${parts[2]||"?"}</strong><span>${parts[1]||"?"}月 · ${parts[0]||""}</span></div><span class="timeline-dot"></span><div class="timeline-items"><div class="timeline-group-title"><strong>${escapeHtml(heading)}</strong><span>${grouped[date].length} 份资料</span></div>${grouped[date].map(documentCard).join("")}</div></div>`;
  }).join(""):`<div class="empty">没有符合筛选条件且日期已确认的资料</div>`;
}
function documentCard(doc){const keys=(doc.key_information||[]).slice(0,2).map(item=>`<li>${escapeHtml(item)}</li>`).join("");return `<a class="doc-card" href="#document/${doc.id}" data-document="${doc.id}"><div class="doc-top"><div class="doc-type-icon" aria-hidden="true">▤</div><div class="doc-main"><div class="doc-meta"><span class="pill green">${escapeHtml(doc.document_type)}</span></div><h4>${escapeHtml(doc.title)}</h4><p>${escapeHtml([doc.hospital,doc.department].filter(Boolean).join(" · ")||"来源待确认")}</p>${keys?`<ul class="key-list">${keys}</ul>`:""}</div><span class="doc-arrow" aria-hidden="true">→</span></div></a>`}
function renderArchive(){$("archiveList").innerHTML=state.documents.length?state.documents.map(documentCard).join(""):`<div class="empty">暂无已归档资料</div>`}
function attachmentPreview(attachment){if(!attachment)return `<div class="empty">没有可预览的原件</div>`;const type=(attachment.mime_type||"").toLowerCase();const name=(attachment.filename||"").toLowerCase();if(type.startsWith("image/")||/\.(png|jpe?g|gif|webp|bmp)$/.test(name))return `<img alt="${escapeHtml(attachment.filename||"原始医疗资料")}" src="${escapeHtml(attachment.preview_url||attachment.content_url)}" decoding="async" fetchpriority="high"${attachment.preview_url?` data-original-src="${escapeHtml(attachment.content_url)}"`:""}>`;if(type==="application/pdf"||name.endsWith(".pdf"))return `<iframe title="原始医疗资料 PDF" src="${escapeHtml(attachment.content_url)}"></iframe>`;return `<div class="empty"><strong>${escapeHtml(attachment.filename||"原始文件")}</strong><p>此文件格式请在新窗口查看</p><a href="${escapeHtml(attachment.content_url)}" target="_blank" rel="noopener">打开原始文件</a></div>`}
function renderDocumentPreview(){const attachments=state.currentDocument?.attachments||[];const index=Math.min(state.previewIndex,Math.max(attachments.length-1,0));const source=attachments[index];$("filePreview").innerHTML=attachmentPreview(source);$("sourceName").textContent=source?.filename||"原始文件待关联";$("sourceThumbs").innerHTML=attachments.length>1?attachments.map((item,i)=>`<button class="src-thumb ${i===index?"active":""}" type="button" data-preview-index="${i}"><span>${escapeHtml(item.filename)}</span></button>`).join(""):"";$("sourceOpen").classList.toggle("hidden",!source);if(source)$("sourceOpen").href=source.content_url}
function labIsMarked(item){const flag=String(item.flag||"").trim();return Boolean(flag&&!/^(正常|normal|阴性|negative|—|-)$/i.test(flag))}
function renderLabResults(){const labs=state.currentDocument?.lab_results||[];const box=$("labResults");if(!labs.length){box.innerHTML="";return}const marked=labs.filter(labIsMarked);const rows=(state.labFilter==="marked"?marked:labs).map(item=>`<tr class="${labIsMarked(item)?"lab-marked":""}"><td class="lab-name">${escapeHtml(item.name)}</td><td><span class="lab-result">${escapeHtml(item.result||"未提供")}</span>${item.flag?`<span class="lab-flag">${escapeHtml(item.flag)}</span>`:""}</td><td>${escapeHtml(item.unit||"—")}</td><td>${escapeHtml(item.reference_range||"—")}</td><td>${item.flag?escapeHtml(item.flag):'<span class="lab-note">—</span>'}</td><td>${state.currentDocument.deleted_at?'已移除':`<button class="btn small" type="button" data-edit-lab-id="${escapeHtml(item.id)}">修正</button>`}</td></tr>`).join("");box.innerHTML=`<div class="lab-block"><div class="lab-summary"><span class="lab-chip">检验项目 ${labs.length} 项</span><span class="lab-chip marked">原报告标记 ${marked.length} 项</span></div><div class="lab-filter"><button type="button" class="${state.labFilter==="all"?"active":""}" data-lab-filter="all">全部项目</button><button type="button" class="${state.labFilter==="marked"?"active":""}" data-lab-filter="marked">仅原报告标记项</button></div><div class="lab-table-wrap"><table class="lab-table"><thead><tr><th>检验项目</th><th>结果</th><th>单位</th><th>参考范围</th><th>提示</th><th>操作</th></tr></thead><tbody>${rows||'<tr><td colspan="6" class="lab-note">没有符合条件的项目</td></tr>'}</tbody></table></div><p class="lab-note">以上仅复现原报告数值与提示，不构成医学判断。</p></div>`}
function renderDocumentDetail(){const doc=state.currentDocument;$("detailEmpty").classList.toggle("hidden",Boolean(doc));$("detailContent").classList.toggle("hidden",!doc);if(!doc)return;$("detailTitle").textContent=doc.title;$("detailMeta").textContent=[doc.primary_date||doc.primary_date_raw,doc.hospital||"医院待确认"].filter(Boolean).join(" · ");$("documentEditBtn").classList.toggle("hidden",Boolean(doc.deleted_at));$("documentTrashBtn").classList.toggle("hidden",Boolean(doc.deleted_at));$("documentRestoreBtn").classList.toggle("hidden",!doc.deleted_at);const fields=[["资料类型",doc.document_type],["主要日期",doc.primary_date||doc.primary_date_raw],["医院",doc.hospital],["科室",doc.department],["医生",doc.doctor],["金额",doc.amount],["关键信息",(doc.key_information||[]).join("\n")]];$("fieldGrid").innerHTML=fields.map((item,index)=>`<div class="field ${index===6?"wide":""}"><label>${item[0]}</label><div>${item[1]?escapeHtml(item[1]):'<span class="null-value">未提供</span>'}</div></div>`).join("");$("parsedContent").textContent=doc.parsed_content||"暂无完整解析内容";renderDocumentPreview();renderLabResults()}
async function openDocument(id){const activeView=document.querySelector(".view.active")?.id.replace("view-","");const origin=["overview","home","metrics","ogtt","costs","archive","drugs"].includes(activeView)?activeView:"archive";state.detailReturnView=origin;state.detailTriggerId=id;state.viewScroll[origin]=window.scrollY;const labels={overview:"数据概览",home:"健康档案",metrics:"健康指标",ogtt:"OGTT",costs:"医疗费用",drugs:"药品管理",archive:"原始资料档案"};const backLabel=labels[origin]||labels.archive;$("detailBack").textContent=`← 返回${backLabel}`;$("detailBack").setAttribute("aria-label",`返回${backLabel}`);try{state.currentDocument=await api.get(`/api/documents/${id}`);state.labFilter="all";state.previewIndex=0;renderDocumentDetail();showView("detail",{refresh:false})}catch(error){toast(errorText(error))}}
function returnFromDetail(){const target=state.detailReturnView||"archive";showView(target,{restoreScroll:true,refresh:false});requestAnimationFrame(()=>requestAnimationFrame(()=>{const card=document.querySelector(`#view-${target} [data-document="${state.detailTriggerId}"]`);card?.focus({preventScroll:true})}))}

const uploadStatusLabels={waiting:"等待上传",uploading:"正在上传原件",uploaded:"等待处理",preprocessing:"正在整理文件",extracting:"视觉模型识别中",pending_confirmation:"等待人工确认",archived:"已归档",failed:"处理失败",timeout:"仍在后台处理"};
const uploadStatusProgress={waiting:0,uploading:12,uploaded:30,preprocessing:48,extracting:76,pending_confirmation:100,archived:100,failed:100,timeout:92};
function renderUploadProgress(){const items=state.uploadItems;if(!items.length)return;$("uploadProgress").classList.remove("hidden");const active=items.filter(item=>!["pending_confirmation","archived","failed","timeout"].includes(item.status));const finished=items.length-active.length;const progress=Math.round(items.reduce((sum,item)=>sum+(uploadStatusProgress[item.status]??0),0)/items.length);$("uploadProgressBar").style.width=`${progress}%`;$("uploadProgressBar").closest(".progress-track").setAttribute("aria-valuenow",String(progress));$("uploadProgressLabel").textContent=`${finished} / ${items.length}`;const status=$("uploadStatus");status.textContent=state.uploadSummary||(items.length===1?(uploadStatusLabels[items[0].status]||items[0].status):`正在处理 ${items.length} 份资料`);status.classList.toggle("processing",Boolean(active.length)&&state.uploadRunning);$("uploadQueue").innerHTML=items.map(item=>`<div class="upload-queue-item ${item.status==="failed"?"failed":""}"><span title="${escapeHtml(item.name)}">${escapeHtml(item.name)}</span><strong>${escapeHtml(item.error||uploadStatusLabels[item.status]||item.status)}</strong></div>`).join("")}
async function handleUpload(event){event.preventDefault();if(state.uploadRunning)return;const files=Array.from($("fileInput").files||[]);if(!files.length)return;state.uploadRunning=true;state.uploadSummary="";state.uploadItems=files.map(file=>({file,name:file.name,status:"waiting",jobId:null,error:null}));$("uploadSubmit").disabled=true;renderUploadProgress();const polls=[];for(const item of state.uploadItems){item.status="uploading";renderUploadProgress();const data=new FormData();data.append("file",item.file);try{const result=await api.post("/api/uploads",data);item.jobId=result.job_id;item.status="uploaded";renderUploadProgress();polls.push(pollJob(result.job_id,item))}catch(error){item.status="failed";item.error=errorText(error);renderUploadProgress()}}await Promise.allSettled(polls);state.uploadRunning=false;const ready=state.uploadItems.filter(item=>item.status==="pending_confirmation").length;const failed=state.uploadItems.filter(item=>item.status==="failed").length;state.uploadSummary=failed?`处理完成：${ready} 份待确认，${failed} 份失败`:`识别完成：${ready} 份资料等待人工确认`;renderUploadProgress();$("uploadSubmit").disabled=false;$("fileInput").value="";$("selectedFile").textContent="点击选择文件";await loadDrafts();toast(failed?"部分资料处理失败，请查看上传队列":"识别完成，请到待确认资料核对")}
async function pollJob(id,item){for(let attempt=0;attempt<120;attempt++){await new Promise(resolve=>setTimeout(resolve,2000));try{const job=await api.get(`/api/jobs/${id}`);item.status=job.status;item.error=job.status==="failed"?(job.error_message||"解析失败"):null;renderUploadProgress();if(["pending_confirmation","archived","failed"].includes(job.status))return}catch(error){item.status="failed";item.error=errorText(error);renderUploadProgress();return}}item.status="timeout";renderUploadProgress()}

async function loadDrafts(){try{const result=await api.get("/api/drafts");state.drafts=result.items;$("pendingBadge").textContent=state.drafts.length;if($("homePendingCount"))$("homePendingCount").textContent=state.drafts.length;const content=state.drafts.length?state.drafts.map(d=>`<article class="draft-card" data-draft="${d.id}"><span class="pill">等待人工确认</span><h4>${escapeHtml(d.payload.document.title)}</h4><p>${escapeHtml(d.payload.document.type)} · ${escapeHtml(d.payload.document.hospital||"来源待确认")}</p></article>`).join(""):`<div class="empty">没有待确认资料</div>`;$("draftList").innerHTML=content;if($("uploadPendingList")){$("uploadPendingList").innerHTML=state.drafts.length?content:"";$("uploadPendingList").closest(".upload-pending-panel")?.classList.toggle("hidden",!state.drafts.length)}}catch(error){toast(errorText(error))}}
function openDraft(id){const draft=state.drafts.find(item=>item.id===id);if(!draft)return;state.currentDraft=draft;$("draftPayload").value=JSON.stringify(draft.payload,null,2);$("draftError").textContent="";$("reviewSource").innerHTML=attachmentPreview(draft.attachment);$("reviewDialog").showModal()}
async function saveDraft(){try{const payload=JSON.parse($("draftPayload").value);state.currentDraft=await api.put(`/api/drafts/${state.currentDraft.id}`,{payload});$("draftError").textContent="";toast("修订已保存")}catch(error){$("draftError").textContent=error instanceof SyntaxError?"JSON 格式不正确":errorText(error)}}
async function confirmDraft(){try{const payload=JSON.parse($("draftPayload").value);await api.post(`/api/drafts/${state.currentDraft.id}/confirm`,{payload});$("reviewDialog").close();await Promise.all([loadDrafts(),loadDocuments(),loadMedications(),loadMetrics(),loadOverview()]);toast("资料已确认并归档，健康趋势已更新")}catch(error){$("draftError").textContent=error instanceof SyntaxError?"JSON 格式不正确":errorText(error)}}

async function loadMedications(){try{const result=await api.get("/api/medications");state.medications=result.items;renderMedications()}catch(error){toast(errorText(error))}}
function medicationDates(med){return med.packages?.length?med.packages.map(item=>item.expiry_date):[med.expiry_date]}
function medicationExpiry(med){const dates=medicationDates(med),known=dates.filter(Boolean),todayDate=today();const soon=known.some(date=>{const days=Math.ceil((Date.parse(`${date}T00:00:00`)-Date.parse(`${todayDate}T00:00:00`))/86400000);return days>=0&&days<=30});return{soon,expired:Boolean(dates.length&&known.length===dates.length&&known.every(date=>date<todayDate)),date:known.filter(date=>date>=todayDate).sort()[0]||known.sort().reverse()[0]||null}}
function category(med){if(med.status==="已停用"||medicationExpiry(med).expired)return"历史用药";return med.status==="正在服用"?"当前用药":"备用 / 药箱"}
function renderMedications(){const groups={"当前用药":[],"备用 / 药箱":[],"历史用药":[]};state.medications.forEach(med=>groups[category(med)].push(med));$("activeDrugCount").textContent=groups["当前用药"].length;$("soonDrugCount").textContent=state.medications.filter(med=>medicationExpiry(med).soon).length;$("expiredDrugCount").textContent=state.medications.filter(med=>medicationExpiry(med).expired).length;const copy={"当前用药":"当前仍在服用的药品","备用 / 药箱":"已有但当前没有持续服用的资料记录","历史用药":"已停用、疗程结束或全部包装已过期的资料记录"};$("drugSections").innerHTML=Object.entries(groups).map(([name,items])=>`<section class="panel drug-section"><div class="drug-section-head"><div><h3>${name}</h3><p>${copy[name]}</p></div><span class="pill">${items.length} 种</span></div><div class="drug-grid">${items.length?items.map(drugCard).join(""):`<div class="empty compact-empty">暂无${name}记录</div>`}</div></section>`).join("");const planned=groups["当前用药"].filter(med=>med.dose_each_time||med.frequency||med.timing);$("todayDrugPlan").innerHTML=planned.length?planned.map(med=>`<article class="plan-item"><strong>${escapeHtml(med.name)}</strong><p>每次：${escapeHtml(med.dose_each_time||"未提供")} · 频次：${escapeHtml(med.frequency||"未提供")}</p><p>时间：${escapeHtml(med.timing||"未提供")}${med.planned_end_date?` · 计划结束：${escapeHtml(med.planned_end_date)}`:""}</p></article>`).join(""):'<div class="empty compact-empty">暂无已确认的服药计划</div>'}
function drugCard(med){const expiry=medicationExpiry(med),actions=med.status==="正在服用"?`<button class="btn small" data-med-action="pause" data-med-id="${escapeHtml(med.id)}">暂停用药</button><button class="btn small" data-med-action="stop" data-med-id="${escapeHtml(med.id)}">停止用药</button>`:med.status==="已停用"?`<button class="btn small primary" data-med-action="start" data-med-id="${escapeHtml(med.id)}">再次开始用药</button>`:expiry.expired?'':`<button class="btn small primary" data-med-action="start" data-med-id="${escapeHtml(med.id)}">开始用药</button>`;return `<article class="drug-card ${expiry.expired?'expired':expiry.soon?'expiring':''}"><div class="drug-card-head"><div><h4>${escapeHtml(med.name)}</h4><p>${escapeHtml([med.generic_name,med.brand_name,med.strength].filter(Boolean).join(" · ")||"规格待确认")}</p></div><span class="pill ${med.status==='正在服用'?'green':''}">${escapeHtml(med.status||"状态待确认")}</span></div><div class="drug-meta"><span><small>每次</small><b>${escapeHtml(med.dose_each_time||"未提供")}</b></span><span><small>每天 / 频次</small><b>${escapeHtml(med.frequency||"未提供")}</b></span><span><small>时间</small><b>${escapeHtml(med.timing||"未提供")}</b></span><span><small>给药途径</small><b>${escapeHtml(med.route||"未提供")}</b></span></div><div class="drug-card-foot"><span>有效期：${escapeHtml(expiry.date||"待确认")}${expiry.expired?' · 已过期':expiry.soon?' · 30 天内到期':''}</span><button class="btn small" type="button" data-med-detail="${escapeHtml(med.id)}">查看详情</button></div><div class="drug-actions">${actions}</div></article>`}
const MEDICATION_FREQUENCIES=['每日 1 次','每日 2 次','每日 3 次','每日 4 次','按需使用','遵医嘱'];
function openMedicationAction(action,id){
  const med=state.medications.find(item=>item.id===id);if(!med)return;
  state.currentMedication=med;
  $("medId").value=id;$("medAction").value=action;$("medVersion").value=med.version;
  $("medDate").value=today();$("medDose").value=med.dose_each_time||'';$("medTiming").value=med.timing||'';
  $("medPlannedEnd").value=med.planned_end_date||'';$("medNote").value='';$("medError").textContent='';
  const frequency=med.frequency||MEDICATION_FREQUENCIES[0];
  $("medFrequency").innerHTML=[...MEDICATION_FREQUENCIES,...(MEDICATION_FREQUENCIES.includes(frequency)?[]:[frequency])]
    .map(item=>`<option value="${escapeHtml(item)}">${escapeHtml(item)}</option>`).join('');
  $("medFrequency").value=frequency;
  $("startFields").classList.toggle('hidden',action!=='start');
  $("medBoundary").classList.toggle('hidden',action!=='start');
  $("medDose").required=action==='start';$("medFrequency").required=action==='start';
  const packages=med.packages||[];
  $("medPackageLabel").classList.toggle('hidden',action!=='start'||packages.length<=1);
  $("medPackage").innerHTML=packages.map(item=>`<option value="${escapeHtml(item.id)}">${escapeHtml([item.batch_number&&`批号 ${item.batch_number}`,item.expiry_date&&`有效期 ${item.expiry_date}`,item.quantity_raw].filter(Boolean).join(' · ')||'包装信息待确认')}</option>`).join('');
  const title=action==='start'?(med.status==='已停用'?'再次开始用药':'开始用药'):action==='pause'?'暂停用药':'停止用药';
  $("medTitle").textContent=`${title} · ${med.name}`;
  $("medMessage").textContent=action==='start'?'确认个人实际用量与频次后，该药品会进入“当前用药”。':action==='pause'?'暂停后会回到“备用 / 药箱”，可在之后重新开始。':'停止后会进入“历史用药”，本次计划与状态记录都会保留。';
  $("medDateLabel").textContent=action==='start'?'开始日期 *':action==='pause'?'暂停日期 *':'实际结束日期 *';
  $("medSubmit").textContent=title;
  $("medDialog").showModal();$("medDate").focus();
}
async function saveMedicationEvent(event){
  event.preventDefault();const action=$("medAction").value;
  const payload={event_type:action,event_date:$("medDate").value,expected_version:Number($("medVersion").value),note:$("medNote").value.trim()||null};
  if(action==='start'){
    payload.dose_each_time=$("medDose").value.trim();payload.frequency=$("medFrequency").value;
    payload.timing=$("medTiming").value.trim()||null;payload.planned_end_date=$("medPlannedEnd").value||null;
    if(payload.planned_end_date&&payload.planned_end_date<payload.event_date){$("medError").textContent='计划结束日期不能早于开始日期。';return}
    if($("medPackage").value)payload.package_id=$("medPackage").value;
  }
  try{await api.post(`/api/medications/${$("medId").value}/events`,payload);$("medDialog").close();await loadMedications();toast("用药状态已记录")}
  catch(error){$("medError").textContent=errorText(error)}
}

async function createInvite(event){event.preventDefault();try{const invitation=await api.post("/api/admin/invitations",{email:$("inviteEmail").value,expires_in_hours:24});$("inviteLink").value=`${location.origin}${location.pathname}?invite=${encodeURIComponent(invitation.token)}`;$("inviteResult").classList.remove("hidden");toast("邀请已创建")}catch(error){toast(errorText(error))}}
async function loadUsers(){if(state.user?.role!=="admin")return;try{const result=await api.get("/api/admin/users");$("userList").innerHTML=result.items.map(user=>`<article class="draft-card"><span class="pill">${user.role==="admin"?"管理员":"普通用户"}</span><h4>${escapeHtml(user.email)}</h4><p>${user.is_active?"账号已启用":"账号已禁用"}</p>${user.id!==state.user.id?`<button class="btn small" data-user-toggle="${user.id}" data-user-active="${user.is_active}">${user.is_active?"禁用账号":"重新启用"}</button>`:""}</article>`).join("")}catch(error){toast(errorText(error))}}
async function toggleUser(id,active){try{await api.patch(`/api/admin/users/${id}`,{is_active:!active});await loadUsers();toast(active?"账号已禁用":"账号已启用")}catch(error){toast(errorText(error))}}
async function resetAuth(){state.user=null;state.documents=[];state.drafts=[];state.medications=[];state.metrics=[];state.metricEntries=[];state.overview=null;state.costSummary=null;state.testSessions=[];state.currentDocument=null;state.currentDraft=null;state.currentMedication=null;state.archiveExpandedMonths?.clear();$("archiveSearch").value="";$("searchInput").value="";$("appShell").classList.add("hidden");$("view-auth").classList.remove("hidden");configureAuth("login")}

$("authPasswordVisibility").addEventListener("click",()=>setAuthPasswordVisibility($("authPassword").type==="password"));
$("authForm").addEventListener("submit",handleAuth);$("logoutBtn").addEventListener("click",async()=>{await api.post("/api/auth/logout",{});resetAuth()});$("uploadForm").addEventListener("submit",handleUpload);$("fileInput").addEventListener("change",()=>{const files=Array.from($("fileInput").files||[]);$("selectedFile").textContent=files.length>1?`已选择 ${files.length} 个文件`:files[0]?.name||"点击选择文件"});$("refreshPending").addEventListener("click",loadDrafts);$("refreshUploadPending").addEventListener("click",loadDrafts);$("refreshUsers").addEventListener("click",loadUsers);$("archiveSearch").addEventListener("input",()=>{clearTimeout(state.searchTimer);state.searchTimer=setTimeout(()=>{if(state.archiveTrashMode&&window.loadTrashDocuments)window.loadTrashDocuments();else renderArchive()},250)});$("searchInput").addEventListener("input",renderHome);$("typeFilter").addEventListener("change",renderHome);$("hospitalFilter").addEventListener("change",renderHome);$("saveDraft").addEventListener("click",saveDraft);$("confirmDraft").addEventListener("click",confirmDraft);$("medForm").addEventListener("submit",saveMedicationEvent);$("medCancel").addEventListener("click",()=>$("medDialog").close());$("inviteForm").addEventListener("submit",createInvite);$("copyInvite").addEventListener("click",()=>navigator.clipboard.writeText($("inviteLink").value).then(()=>toast("邀请链接已复制")));$("exportBtn").addEventListener("click",()=>location.assign("/api/export"));
document.body.addEventListener("click",event=>{const detailBack=event.target.closest("[data-detail-back]");if(detailBack){returnFromDetail();return}const nav=event.target.closest("[data-view],[data-go]");if(nav)showView(nav.dataset.view||nav.dataset.go);const doc=event.target.closest("[data-document]");if(doc){event.preventDefault();openDocument(doc.dataset.document)}const draft=event.target.closest("[data-draft]");if(draft)openDraft(draft.dataset.draft);const med=event.target.closest("[data-med-action]");if(med)openMedicationAction(med.dataset.medAction,med.dataset.medId);const user=event.target.closest("[data-user-toggle]");if(user)toggleUser(user.dataset.userToggle,user.dataset.userActive==="true");const preview=event.target.closest("[data-preview-index]");if(preview){state.previewIndex=Number(preview.dataset.previewIndex);renderDocumentPreview()}const labFilter=event.target.closest("[data-lab-filter]");if(labFilter){state.labFilter=labFilter.dataset.labFilter;renderLabResults()}});
document.body.addEventListener("keydown",event=>{if((event.key==="Enter"||event.key===" ")&&event.target.matches("[data-document]")){event.preventDefault();openDocument(event.target.dataset.document)}});
bootstrap();

document.addEventListener("error",event=>{const image=event.target;if(image instanceof HTMLImageElement&&image.dataset.originalSrc){const original=image.dataset.originalSrc;delete image.dataset.originalSrc;image.src=original}},true);
